# Lecture 9: Functions #

In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions ##  

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [2]:
def triple(x):
    return 3 * x

In [3]:
triple(3)

9

We can also assign a value to a name, and call the function on the name:

In [4]:
num = 4

In [5]:
triple(num)

12

In [6]:
triple(num * 5)

60

## The Anatomy of a Function ##  
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
      return return_expression
```

## Functions are Type-Agnostic  ## 

In [7]:
triple('ha')

'hahaha'

In [8]:
np.arange(4)

array([0, 1, 2, 3])

Feed the array above into our function `triple` to see what is produced:

In [9]:
triple(np.arange(4))

array([0, 3, 6, 9])

### Discussion Question ###

```python
def f(s):     
      return np.round(s / sum(s) * 100, 2)
```

In [10]:
def percent_of_total(s):
    return np.round(s / sum(s) * 100, 2)

In [11]:
first_four=make_array(1,2,3,4)
first_four

array([1, 2, 3, 4])

In [12]:
percent_of_total(first_four)

array([ 10.,  20.,  30.,  40.])

In [13]:
percent_of_total(make_array(1, 213, 38))

array([  0.4 ,  84.52,  15.08])

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

In [14]:
def hypotenuse(x, y):
    hypot_squared = (x ** 2 + y ** 2)
    hypot = hypot_squared ** 0.5
    return hypot

In [15]:
hypotenuse(1, 2)

2.23606797749979

In [16]:
hypotenuse(3, 4)

5.0

We could've typed the body all in one line. Do you find this more readable or less readable than the original version?

In [17]:
def hypotenuse(x,y):
    return (x ** 2 + y ** 2) ** 0.5

In [18]:
hypotenuse(9, 12)

15.0

### Example: A function that takes the year of birth of a person and produces their age in years. ###

In [19]:
def age(year):
    age = 2023 - year
    return age

In [20]:
age(1942)

81

Now add some bells and whistles:  Take person's name and year of birth (two arguments). Produce a sentence that states how old they are.

In [21]:
def name_and_age(name, year):
    return name + ' is ' + str(age(year)) + ' years old.'

In [22]:
name_and_age('Joe', 1942)

'Joe is 81 years old.'

## Apply ##

In [23]:
staff = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
staff

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

In [ ]:
staff.apply(age, 'Birth Year')

array([ 38,  35,  56, 119])

In [ ]:
make_array(age(staff.column('Birth Year').item(0)),
           age(staff.column('Birth Year').item(1)),
           age(staff.column('Birth Year').item(2)),
           age(staff.column('Birth Year').item(3)))

array([ 38,  35,  56, 119])

In [26]:
staff.apply(name_and_age, 'Person', 'Birth Year')

array(['Jim is 38 years old.', 'Pam is 35 years old.',
       'Michael is 56 years old.', 'Creed is 119 years old.'],
      dtype='<U24')