In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Types ##

In [2]:
type(10)

int

In [3]:
a = 10
type(a)

int

In [4]:
type(4.5)

float

In [5]:
type('abc')

str

In [6]:
type(abs)

builtin_function_or_method

In [7]:
skyscrapers = Table.read_table('data/skyscrapers.csv')
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [8]:
type(skyscrapers)

datascience.tables.Table

In [9]:
type(False)

bool

**Question:** what will `type(int(float('3.14159')))` return?

In [ ]:
type(int(float('3.14159')))

## Arrays

In [10]:
heights = make_array(67, 60, 71, 63, 65) # make an array
heights

array([67, 60, 71, 63, 65])

In [11]:
heights + 10

array([77, 70, 81, 73, 75])

In [12]:
heights / 12

array([ 5.58333333,  5.        ,  5.91666667,  5.25      ,  5.41666667])

In [13]:
heights * 2

array([134, 120, 142, 126, 130])

In [14]:
heights + heights

array([134, 120, 142, 126, 130])

In [15]:
heights + make_array(0, 100, 1000, 10000, 1000000)

array([     67,     160,    1071,   10063, 1000065])

In [16]:
len(heights)

5

In [17]:
sum(heights)

326

In [18]:
sum(heights) / len(heights)

65.200000000000003

In [21]:
np.average(heights)

65.200000000000003

In [22]:
rodents = make_array('marmots', 'gophers', 'capybaras')
rodents

array(['marmots', 'gophers', 'capybaras'],
      dtype='<U9')

In [23]:
np.sort(rodents)

array(['capybaras', 'gophers', 'marmots'],
      dtype='<U9')

In [24]:
heights

array([67, 60, 71, 63, 65])

In [28]:
heights.item(1)

60

In [29]:
rodents.item(0)

'marmots'

**Question:** how do we get the last item in the `heights` array?

In [32]:
heights.item(-2)

63

In [ ]:
heights.item(5)

In [33]:
type(heights)

numpy.ndarray

## Columns of Tables are Arrays ##

In [34]:
skyscrapers = Table.read_table('data/skyscrapers.csv')
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [35]:
# Remember what does the table where() function does?
sf = skyscrapers.where('city', 'San Francisco')
sf

name                  | material  | city          | height | completed
Transamerica Pyramid  | composite | San Francisco | 260    | 1972
555 California Street | steel     | San Francisco | 237.44 | 1969
345 California Center | steel     | San Francisco | 211.84 | 1986
Millennium Tower      | concrete  | San Francisco | 196.6  | 2009

In [36]:
# Remember what the table select() function does?
sf.select('height')

height
260
237.44
211.84
196.6

In [37]:
type(sf.select('height'))

datascience.tables.Table

In [38]:
sf.column('height')

array([ 260.        ,  237.44000244,  211.83999634,  196.6000061 ])

In [39]:
type(sf.column('height')) 

numpy.ndarray

In [40]:
np.average(sf.column('height'))

226.470001220705

**Question:** How do we create an array with the numbers 0, 1, 2, 3, 4, 5, 6?

In [42]:
a = make_array(0, 1, 2, 3, 4, 5, 6)
a

array([0, 1, 2, 3, 4, 5, 6])

Is there an easier way?

## Ranges ##

In [43]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [44]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [46]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
# What will the last number of this array be?
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
# What will the last number of this array be?
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

**Question 1:** can we create an array from 0 to 100, including 100, with a step increase of 10?

In [56]:
np.arange(0, 109, 10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

**Question 2:** can we create an array from 100 to 200, not including 200, with a step increase of 10?

In [50]:
np.arange(100, 200, 10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

**Challenge question:** can we create an array that *decreases* from 10 to 0 (including both 10 and 0)?

In [51]:
np.arange(10, -1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
help(np.arange)

## Creating a Table from Scratch ##

In [57]:
streets = make_array('dp', 'sabado', 'trigo', 'pasado', 'sueno')
streets

array(['dp', 'sabado', 'trigo', 'pasado', 'sueno'],
      dtype='<U6')

In [58]:
Table()

In [59]:
iv = Table().with_column('Streets', streets)
iv

Streets
dp
sabado
trigo
pasado
sueno

In [60]:
blocks_from_beach = np.arange(len(streets))
blocks_from_beach

array([0, 1, 2, 3, 4])

In [61]:
iv.with_column('Blocks from Beach', blocks_from_beach)

Streets | Blocks from Beach
dp      | 0
sabado  | 1
trigo   | 2
pasado  | 3
sueno   | 4

In [63]:
iv
# Why isn't there a Blocks from Beach column?

Streets
dp
sabado
trigo
pasado
sueno

In [64]:
iv = iv.with_column('Blocks from Beach', blocks_from_beach)
iv

Streets | Blocks from Beach
dp      | 0
sabado  | 1
trigo   | 2
pasado  | 3
sueno   | 4

In [65]:
iv

Streets | Blocks from Beach
dp      | 0
sabado  | 1
trigo   | 2
pasado  | 3
sueno   | 4

## Reading a Table from a File  ##

In [ ]:
int(sum(heights))

In [ ]:
strings_array + make_array('A', 'b', 'c')

In [66]:
du_bois = Table.read_table('data/du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [76]:
# Which group ("CLASS") spent the highest percentage on rent?
rent_status_class_only = du_bois.select('RENT', 'STATUS','CLASS')
rent_status_class_only_sorted = rent_status_class_only.sort('RENT', descending = True)
rent_status_class_only_sorted.take(0).select('CLASS') # take first row, selected Class column 

# The Class, categoried as Fair, with an annual income of $300-400, spent the highest percentage on rent, 23%.
rent_status_class_only_sorted

RENT | STATUS      | CLASS
0.23 | FAIR        | 300-400
0.22 | POOR        | 200-300
0.19 | POOR        | 100-200
0.18 | FAIR        | 400-500
0.13 | COMFORTABLE | 500-750
0    | COMFORTABLE | 750-1000
0    | WELL-TO-DO  | 1000 and over

In [82]:
du_bois.select('STATUS') # table format

STATUS
POOR
POOR
FAIR
FAIR
COMFORTABLE
COMFORTABLE
WELL-TO-DO

In [84]:
du_bois.column('STATUS') # extracting a column from a table, in an array format
# n-dimensional array from the numpy package
# array form

array(['POOR', 'POOR', 'FAIR', 'FAIR', 'COMFORTABLE', 'COMFORTABLE',
       'WELL-TO-DO'],
      dtype='<U11')

In [85]:
du_bois.select('STATUS')

STATUS
POOR
POOR
FAIR
FAIR
COMFORTABLE
COMFORTABLE
WELL-TO-DO

In [86]:
du_bois.column('STATUS')

array(['POOR', 'POOR', 'FAIR', 'FAIR', 'COMFORTABLE', 'COMFORTABLE',
       'WELL-TO-DO'],
      dtype='<U11')

In [87]:
heights.size

5

In [88]:
du_bois.column('ACTUAL AVERAGE')

array([  139.1 ,   249.45,   335.66,   433.82,   547.  ,   880.  ,  1125.  ])

In [89]:
du_bois.column('FOOD')

array([ 0.43,  0.47,  0.43,  0.37,  0.31,  0.37,  0.29])

In [91]:
139.1*.43
# on average, the poorest class spent $59.81 on food per year. That was 43% of their annual income.

59.812999999999995

In [90]:
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')


array([  59.813 ,  117.2415,  144.3338,  160.5134,  169.57  ,  325.6   ,
        326.25  ])

In [92]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD') # find out in dollar amounts what each class
# spent on food per year, on aerage
du_bois = du_bois.with_column(
    'Food $',
    food_dollars # adding food_dollars array to the du_bois table, and calling it 'Food $'
)
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [93]:
du_bois.set_format('FOOD', PercentFormatter)

CLASS         | ACTUAL AVERAGE | RENT | FOOD   | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 43.00% | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 47.00% | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 43.00% | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 37.00% | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 31.00% | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 37.00% | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 29.00% | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [ ]:
du_bois.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')

In [ ]:
du_bois.column('FOOD')

## Selecting data in a column ##

In [ ]:
movies = Table.read_table('data/movies_by_year_with_ticket_price.csv')
movies.show()

In [ ]:
gross_in_dollars = movies.column('Total Gross') * 1e6
tix_sold = gross_in_dollars / movies.column('Average Ticket Price')

In [ ]:
movies = movies.with_column('Tickets sold', tix_sold)

In [ ]:
movies.show(4)

In [ ]:
movies.set_format('Tickets sold', NumberFormatter)

In [ ]:
movies.plot('Year', 'Tickets sold')

In [ ]:
movies.where('Year', are.between(2000, 2005))

In [ ]:
movies.where('Year', 2002)

In [ ]:
movies.where('Year', are.equal_to(2002))

In [ ]:
movies.where('#1 Movie', are.containing('Harry Potter'))

In [ ]:
movies.take(np.arange(2, 5))